### ISSUE TITLE
ZV Služby

### ISSUE THREAD

**Issue by IxAriela** [saurinne/Koderka_du7_cestovka#1]
Ahoj,

pěkná práce. I tak se ale našlo pár drobností, i důležitějších věcí na opravu.

- čistě teoreticky, tlačítka vůbec nepotřebovaly obalový div, stačilo dát tu třídu na ul. Ničemu to samozřejmě nevadí, ale ušetřený řádek se hodí :)
- u třídy .kartičky máš v html vždy přídavek, ten je ale pokaždé jiný. Jednou .prvni_karticky, pak .podruhe. Bylo by fajn to mít sjednocené, i když z ostatního kódu usuzuji, že ti to spíš uteklo, než že by to byl záměr.
- margin-top u kartiček bych vynulovala už u tabletové verze, čistě kvůli přehlednosti. Líp se hledá mezera na obalu než na vnitřním prvku. 
- A naopak bych klidně tu mezeru na section nastavila už od mobilu, raději než na nadpisu.
- Mezera mezi section by měla být větší než máš, teď to v těch užších verzích trošku zaniká s mezerou pod textem a není to tak dobře oddělené.
- vertikální zarovnání na střed většinou dělám pomocí flexu (display: flex; flex-direction: column; justify-content: center;), nemám ráda tohle zarovnávání marginem. Čistě z praktických důvodů, vedlejší blog obsahuje text, řádky se zalamují různě  a tím se mění i výška vedlejšího prvku. A tedy pak nesedí to středové zarovnání. Tady je toho textu málo, tak je to v podstatě jedno, nepůjde to vidět, ale není to úplně dobrý postup.

Oprav prosím:
- [x] font-family nastavujeme vždy na body, na jednotlivé komponeny (např. nadpisy), až když se liší od toho obecného. Nastavovat je jednotlivě je zbytečně zdlouhavé a lehce se na něco zapomene. Což se stalo i u tebe a tlačítka máš jiným písmem než zbytek, protože jsi  zapomněla na `a`.
- [x] nikdy nepíšeme styly do html. To se dělalo dříve, občas se to používá třeba u e-mailingů, ale na normálních webovkách nikdy. Co je v html téměř nejde přepsat přes css a to nechceš. Jo, občas to můžeš vidět i u webů přes průzkumníka, ale to tam dodává JS, to je ještě jiný případ.
- [x] u kartiček ti chybí stíny, které v návrhu vidím

**Comment by saurinne** [comment]
Ahoj, díky. Mělo by to být opraveno, kdyžtak kuknu.
